export const ActionTypes = {
    SETUSER:'SETUSER',
    SETDATA:'SETDATA',
    SET_ELEMENTARY_DATA:'SET_ELEMENTARY_DATA',
    SET_PREINTERMEDIATE_DATA:'SET_PREINTERMEDIATE_DATA',
    SET_INTERMEDIATE_DATA:'SET_INTERMEDIATE_DATA',
    SET_ADVANCED_DATA:'SET_ADVANCED_DATA'
}